version: '3.8'

services:
  php:
    container_name: php
    networks:
      - app
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - .:/var/www/html  
      - ./docker/entrypoint.sh:/usr/local/bin/entrypoint.sh 
    expose:
      - 9000  
    entrypoint: /bin/bash -c "/usr/local/bin/entrypoint.sh"

  nginx:
    container_name: nginx
    image: nginx:alpine 
    networks:
      - app
    volumes:
      - .:/var/www/html  
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  
    ports:
      - "8080:80" 

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql_data:
